# Generated by Django 2.2.16 on 2020-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='Logo')),
                ('description', models.TextField()),
                ('quality', models.IntegerField()),
                ('price', models.FloatField()),
                ('Sale_Date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
