# Generated by Django 2.2.16 on 2020-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, default='photo.jpg', upload_to='Logo'),
        ),
    ]
